// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xagbhvhqtgybmzfkcxoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhZ2JodmhxdGd5Ym16ZmtjeG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODM1ODksImV4cCI6MjA3MDQ1OTU4OX0.VaJbNTXyjEPZMc7F-KYdkNxfbnDuxppxTWz7VA8BLV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});